version: '3'

services:
  app:
    container_name: lara-app
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    entrypoint: ./docker/entrypoint.sh
    env_file:
      - .env
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build: ./docker/nginx
    container_name: lara-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    build: ./docker/mysql
    container_name: lara-db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=secret
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: lara-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

networks:
  app-network:
    driver: bridge
