version: '3'

services:
  app:
    container_name: lara-app
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    entrypoint: ./docker/entrypoint.sh
    env_file:
      - .env
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    container_name: lara-nginx
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    container_name: lara-db
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=secret
    networks:
      - app-network

  redis:
    container_name: lara-redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  zookeeper:
    container_name: lara-zookeeper
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    container_name: lara-lafka
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  app-network:
    driver: bridge
